services:
  # Web service for the Flask application
  - type: web
    name: giveaway-bot-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: giveaway-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: REDIRECT_URI
        value: https://your-app-name.onrender.com/auth/twitch/callback
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: SESSION_COOKIE_HTTPONLY
        value: "true"
      - key: SESSION_COOKIE_SAMESITE
        value: Lax
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FILE
        value: /tmp/app.log
      - key: RATE_LIMIT_DEFAULT
        value: 10/minute
      - key: RATE_LIMIT_AUTH
        value: 5/minute

  # Worker service for the chatbot
  - type: worker
    name: giveaway-bot-worker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: giveaway-db
          property: connectionString
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FILE
        value: /tmp/worker.log

databases:
  - name: giveaway-db
    databaseName: giveaway_db
    user: giveaway_user
    plan: free 